version: "3.8"

services:
  django:
    build: .
    container_name: notification-service
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8002"
    volumes:
      - .:/app
    ports:
      - "8002:8002"
  
  queue:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    environment:
      - CLOUDAMQP_URL=amqps://amjpxqaz:2_lHNNUatQZhMP5xbNO391K9-wx7GqMQ@puffin.rmq2.cloudamqp.com/amjpxqaz
